language: python
python: 3.5
sudo: false
env:
 - TOXENV=py27
 - TOXENV=py35
install:
 - pip install -U tox twine wheel codecov
script: tox
after_success:
  - codecov
cache:
  directories:
    - $HOME/.cache/pip
